services:
  postgres:
    image: postgres:17

    container_name: interviewos-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_os

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis: 
    image: redis:7

    container_name: interviewos-redis

    ports: 
      - "6379:6379"

volumes:
  postgres_data: